dev-fix-testcontainers-NoClassDefFoundError: Re-introduced several checks in TimeSeriesRDBClient to ensure descriptive exception messages; replaced inefficient context.meta.() queries for central lookup table with more efficient queries